#! /bin/bash  
if [ -z "$1" ]; then   
echo "`basename $0` {start|stop}"  
exit  
fi  
  
case "$1" in  
start)  
      /usr/bin/xvfb :7 -ac -screen 0 1024x768x8 &  
;;  
stop)  
      killall xvfb  
;;  
esac
